import type { MasoomeenId, MasoomeenMeta } from '../types';

export const MASOOMEEN_CATALOG: MasoomeenMeta[] = [
  {
    id: 'masoom_prophet',
    order: 1,
    role: 'prophet',
    titles: { en: 'Prophet Muhammad', ur: 'نبی محمدؐ', ar: 'النبي محمد' },
    honorific: { en: '(s)', ur: 'ؐ', ar: 'ص' },
    epithet: { en: 'Seal of the Prophets', ur: 'خاتم الانبیاء', ar: 'خاتم الأنبياء' },
    birthHijri: '53 BH (~570 CE)',
    deathHijri: '11 AH (632 CE)',
    birthPlace: { en: 'Mecca', ur: 'مکہ', ar: 'مكة' },
    shrine: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    accentColor: '#4A6FA5',
  },
  {
    id: 'masoom_fatima',
    order: 2,
    role: 'lady',
    titles: { en: 'Sayyida Fatima', ur: 'سیدہ فاطمہؑ', ar: 'السيدة فاطمة' },
    honorific: { en: '(sa)', ur: 'ؑ', ar: 'س' },
    epithet: { en: 'Lady of the Worlds', ur: 'سیدۃ نساء العالمین', ar: 'سيدة نساء العالمين' },
    birthHijri: '~5 BH',
    deathHijri: '11 AH',
    birthPlace: { en: 'Mecca', ur: 'مکہ', ar: 'مكة' },
    shrine: { en: 'Medina (Jannat al-Baqi)', ur: 'مدینہ (بقیع)', ar: 'البقيع' },
    accentColor: '#7B4B6A',
  },
  {
    id: 'masoom_ali',
    order: 3,
    role: 'imam',
    titles: { en: 'Imam Ali', ur: 'امام علیؑ', ar: 'الإمام علي' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Amir al-Muminin', ur: 'امیر المومنین', ar: 'أمير المؤمنين' },
    birthHijri: '23 BH (600 CE)',
    deathHijri: '40 AH (661 CE)',
    birthPlace: { en: 'Inside the Kaaba, Mecca', ur: 'کعبہ، مکہ', ar: 'داخل الكعبة' },
    shrine: { en: 'Najaf', ur: 'نجف', ar: 'النجف' },
    accentColor: '#3D9B8A',
  },
  {
    id: 'masoom_hasan',
    order: 4,
    role: 'imam',
    titles: { en: 'Imam Hasan', ur: 'امام حسنؑ', ar: 'الإمام الحسن' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Al-Mujtaba', ur: 'مجتبی', ar: 'المجتبى' },
    birthHijri: '3 AH',
    deathHijri: '50 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Medina (Jannat al-Baqi)', ur: 'مدینہ (بقیع)', ar: 'البقيع' },
    accentColor: '#5A8A7A',
  },
  {
    id: 'masoom_husayn',
    order: 5,
    role: 'imam',
    titles: { en: 'Imam Husayn', ur: 'امام حسینؑ', ar: 'الإمام الحسين' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Sayyid al-Shuhada', ur: 'سید الشہداء', ar: 'سيد الشهداء' },
    birthHijri: '4 AH',
    deathHijri: '61 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Karbala', ur: 'کربلا', ar: 'كربلاء' },
    accentColor: '#8B3A3A',
  },
  {
    id: 'masoom_zainulabideen',
    order: 6,
    role: 'imam',
    titles: { en: 'Imam Zain ul-Abideen', ur: 'امام زین العابدینؑ', ar: 'الإمام زين العابدين' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Sayyid al-Sajideen', ur: 'سید الساجدین', ar: 'سيد الساجدين' },
    birthHijri: '38 AH',
    deathHijri: '95 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Medina (Jannat al-Baqi)', ur: 'مدینہ (بقیع)', ar: 'البقيع' },
    accentColor: '#6B7A9B',
  },
  {
    id: 'masoom_baqir',
    order: 7,
    role: 'imam',
    titles: { en: 'Imam Muhammad al-Baqir', ur: 'امام محمد باقرؑ', ar: 'الإمام محمد الباقر' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Splitter of Knowledge', ur: 'باقر العلوم', ar: 'باقر العلوم' },
    birthHijri: '57 AH',
    deathHijri: '114 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Medina (Jannat al-Baqi)', ur: 'مدینہ (بقیع)', ar: 'البقيع' },
    accentColor: '#4A7A6A',
  },
  {
    id: 'masoom_sadiq',
    order: 8,
    role: 'imam',
    titles: { en: 'Imam Jafar al-Sadiq', ur: 'امام جعفر صادقؑ', ar: 'الإمام جعفر الصادق' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Founder of Ja\'fari Fiqh', ur: 'بani مذہب جعفری', ar: 'مؤسس المذهب الجعفري' },
    birthHijri: '83 AH',
    deathHijri: '148 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Medina (Jannat al-Baqi)', ur: 'مدینہ (بقیع)', ar: 'البقيع' },
    accentColor: '#3D7A8A',
  },
  {
    id: 'masoom_kazim',
    order: 9,
    role: 'imam',
    titles: { en: 'Imam Musa al-Kazim', ur: 'امام موسیٰ کاظمؑ', ar: 'الإمام موسى الكاظم' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Al-Kazim', ur: 'کاظم', ar: 'الكاظم' },
    birthHijri: '128 AH',
    deathHijri: '183 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Kadhimiya, Baghdad', ur: 'کاظمین', ar: 'الكاظمية' },
    accentColor: '#5A6A8A',
  },
  {
    id: 'masoom_reza',
    order: 10,
    role: 'imam',
    titles: { en: 'Imam Ali al-Rida', ur: 'امام علی رضاؑ', ar: 'الإمام علي الرضا' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Al-Rida', ur: 'رضا', ar: 'الرضا' },
    birthHijri: '148 AH',
    deathHijri: '203 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Mashhad', ur: 'مشهد', ar: 'مشهد' },
    accentColor: '#6A5A8A',
  },
  {
    id: 'masoom_jawad',
    order: 11,
    role: 'imam',
    titles: { en: 'Imam Muhammad al-Jawad', ur: 'امام محمد تقیؑ', ar: 'الإمام محمد الجواد' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Al-Jawad', ur: 'جواد', ar: 'الجواد' },
    birthHijri: '195 AH',
    deathHijri: '220 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Kadhimiya, Baghdad', ur: 'کاظمین', ar: 'الكاظمية' },
    accentColor: '#4A8A7A',
  },
  {
    id: 'masoom_hadi',
    order: 12,
    role: 'imam',
    titles: { en: 'Imam Ali al-Hadi', ur: 'امام علی نقیؑ', ar: 'الإمام علي الهادي' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Al-Hadi', ur: 'ہادی', ar: 'الهادي' },
    birthHijri: '212 AH',
    deathHijri: '254 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Samarra', ur: 'سامرّا', ar: 'سامراء' },
    accentColor: '#7A6A5A',
  },
  {
    id: 'masoom_askari',
    order: 13,
    role: 'imam',
    titles: { en: 'Imam Hasan al-Askari', ur: 'امام حسن عسکریؑ', ar: 'الإمام الحسن العسكري' },
    honorific: { en: '(as)', ur: 'ؑ', ar: 'ع' },
    epithet: { en: 'Al-Askari', ur: 'عسکری', ar: 'العسكري' },
    birthHijri: '232 AH',
    deathHijri: '260 AH',
    birthPlace: { en: 'Medina', ur: 'مدینہ', ar: 'المدينة' },
    shrine: { en: 'Samarra', ur: 'سامرّا', ar: 'سامراء' },
    accentColor: '#5A7A8A',
  },
  {
    id: 'masoom_mahdi',
    order: 14,
    role: 'imam',
    titles: { en: 'Imam al-Mahdi', ur: 'امام مہدیؑ', ar: 'الإمام المهدي' },
    honorific: { en: '(aj)', ur: 'ؑ عجل اللہ فرجہ', ar: 'ع' },
    epithet: { en: 'Al-Qa\'im', ur: 'قائم آل محمد', ar: 'القائم' },
    birthHijri: '255 AH',
    deathHijri: '— (in occultation)',
    birthPlace: { en: 'Samarra', ur: 'سامرّا', ar: 'سامراء' },
    shrine: { en: 'Occultation', ur: 'غیبت', ar: 'الغيبة' },
    accentColor: '#C4A962',
  },
];

export function getMasoomeenMeta(id: MasoomeenId): MasoomeenMeta | undefined {
  return MASOOMEEN_CATALOG.find((m) => m.id === id);
}

export const MASOOMEEN_BY_ID = Object.fromEntries(
  MASOOMEEN_CATALOG.map((m) => [m.id, m]),
) as Record<MasoomeenId, MasoomeenMeta>;
