import type { AdminRole } from '../decorators/roles.decorator';

/** Phase 1 canonical permission matrix — source of truth for guard + RBAC UI. */
export const ROLE_PERMISSIONS: Record<AdminRole, string[]> = {
  moderator: [
    'users.read',
    'analytics.read',
    'cms.read',
    'cms.write',
    'guides.read',
    'events.read',
    'flags.read',
    'health.read',
    'notifications.read',
    'media.read',
    'audit.read',
    'support.read',
  ],
  admin: [
    'users.read',
    'users.write',
    'analytics.read',
    'analytics.export',
    'notifications.read',
    'notifications.write',
    'cms.read',
    'cms.write',
    'cms.publish',
    'guides.read',
    'guides.write',
    'events.read',
    'events.write',
    'flags.read',
    'flags.write',
    'health.read',
    'logs.read',
    'security.read',
    'ai.read',
    'media.read',
    'media.write',
    'rbac.read',
    'audit.read',
    'support.read',
    'support.write',
  ],
  super_admin: [
    'users.read',
    'users.write',
    'users.delete',
    'analytics.read',
    'analytics.export',
    'notifications.read',
    'notifications.write',
    'cms.read',
    'cms.write',
    'cms.publish',
    'guides.read',
    'guides.write',
    'events.read',
    'events.write',
    'flags.read',
    'flags.write',
    'health.read',
    'logs.read',
    'security.read',
    'security.write',
    'ai.read',
    'ai.write',
    'media.read',
    'media.write',
    'rbac.read',
    'rbac.write',
    'audit.read',
    'support.read',
    'support.write',
  ],
};

export const ALL_PERMISSION_SLUGS = [
  ...new Set(Object.values(ROLE_PERMISSIONS).flat()),
].sort();
