import type { PrayerAcademyMeta } from '../types';

export const PRAYER_ACADEMY_CATALOG: PrayerAcademyMeta[] = [
  {
    id: 'salat_fajr',
    slug: 'fajr',
    category: 'obligatory_daily',
    obligation: 'wajib',
    titles: { en: 'Fajr', ur: 'فجر', ar: 'الفجر' },
    subtitles: { en: 'Dawn prayer', ur: 'صبح کی نماز', ar: 'صلاة الصبح' },
    purpose: {
      en: 'First obligatory prayer of the day; two wajib rakats.',
      ur: 'دن کی پہلی واجب نماز؛ دو واجب رکعتیں۔',
      ar: 'أول صلاة واجبة في اليوم؛ ركعتان واجبتان.',
    },
    description: {
      en: 'Learn Fajr according to Fiqh Jafariya — timing, conditions, qunoot, and step-by-step method.',
      ur: 'فقہ جعفریہ کے مطابق فجر — وقت، شرائط، قنوت اور مرحلہ وار طریقہ۔',
      ar: 'تعلّم صلاة الفجر وفق الفقه الجعفري — الوقت والشروط والقنوت والخطوات.',
    },
    estimatedMinutes: 8,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['daily', 'wajib', 'fajr'],
    featured: true,
  },
  {
    id: 'salat_dhuhr',
    slug: 'dhuhr',
    category: 'obligatory_daily',
    obligation: 'wajib',
    titles: { en: 'Dhuhr', ur: 'ظہر', ar: 'الظهر' },
    subtitles: { en: 'Noon prayer', ur: 'دوپہر کی نماز', ar: 'صلاة الظهر' },
    purpose: {
      en: 'Four wajib rakats at midday; recommended nafl before/after.',
      ur: 'دوپہر میں چار واجب رکعتیں؛ پہلے/بعد مستحب نفل۔',
      ar: 'أربع ركعات واجبة في الظهر؛ نافلة مستحبة قبل/بعد.',
    },
    description: {
      en: 'Complete Dhuhr guide with 4-rakat structure and Jafari middle-rakat rules.',
      ur: 'چار رکعت والی ظہر — درمیانی رکعتوں کے جعفری احکام سمیت۔',
      ar: 'دليل الظهر الكامل مع أحكام الركعات الوسطى الجعفرية.',
    },
    estimatedMinutes: 12,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['daily', 'wajib', 'dhuhr'],
  },
  {
    id: 'salat_asr',
    slug: 'asr',
    category: 'obligatory_daily',
    obligation: 'wajib',
    titles: { en: 'Asr', ur: 'عصر', ar: 'العصر' },
    subtitles: { en: 'Afternoon prayer', ur: 'سہ پہر کی نماز', ar: 'صلاة العصر' },
    purpose: {
      en: 'Four wajib rakats in the afternoon; no qunoot in 2nd rakat.',
      ur: 'سہ پہر میں چار واجب رکعتیں؛ دوسری رکعت میں قنوت نہیں۔',
      ar: 'أربع ركعات واجبة في العصر؛ لا قنوت في الركعة الثانية.',
    },
    description: {
      en: 'Asr prayer method, preferred time (fadhilat), and 4-rakat Jafari recitation.',
      ur: 'عصر کا طریقہ، فضیلت کا وقت، اور چار رکعت جعفری قراءت۔',
      ar: 'طريقة العصر ووقت الفضيلة وقراءة الركعات الأربع.',
    },
    estimatedMinutes: 12,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['daily', 'wajib', 'asr'],
  },
  {
    id: 'salat_maghrib',
    slug: 'maghrib',
    category: 'obligatory_daily',
    obligation: 'wajib',
    titles: { en: 'Maghrib', ur: 'مغرب', ar: 'المغرب' },
    subtitles: { en: 'Sunset prayer', ur: 'غروب کی نماز', ar: 'صلاة المغرب' },
    purpose: {
      en: 'Three wajib rakats after sunset; qunoot in 2nd rakat.',
      ur: 'غروب کے بعد تین واجب رکعتیں؛ دوسری میں قنوت۔',
      ar: 'ثلاث ركعات واجبة بعد الغروب؛ قنوت في الثانية.',
    },
    description: {
      en: 'Maghrib timing (including Jafari delay), 3-rakat flow, and recommended 2 nafl after.',
      ur: 'مغرب کا وقت (جعفری مہلت سمیت)، تین رکعت، اور بعد میں دو مستحب نفل۔',
      ar: 'وقت المغرب (مع المهل الجعفري) وثلاث ركعات ونافلتين مستحبتين بعدها.',
    },
    estimatedMinutes: 10,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['daily', 'wajib', 'maghrib'],
  },
  {
    id: 'salat_isha',
    slug: 'isha',
    category: 'obligatory_daily',
    obligation: 'wajib',
    titles: { en: 'Isha', ur: 'عشاء', ar: 'العشاء' },
    subtitles: { en: 'Night prayer', ur: 'رات کی نماز', ar: 'صلاة العشاء' },
    purpose: {
      en: 'Four wajib rakats at night; followed by recommended Shaf\' and Witr.',
      ur: 'رات میں چار واجب رکعتیں؛ بعد میں مستحب شفع و وتر۔',
      ar: 'أربع ركعات واجبة ليلًا؛ يليها الشفع والوتر مستحبان.',
    },
    description: {
      en: 'Isha wajib prayer plus overview of Shaf\' (2) and Witr (1) nafl.',
      ur: 'عشاء کی واجب نماز اور شفع (۲) و وتر (۱) کا خلاصہ۔',
      ar: 'صلاة العشاء الواجبة ونبذة عن الشفع والوتر.',
    },
    estimatedMinutes: 14,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['daily', 'wajib', 'isha'],
  },
  {
    id: 'namaz_e_ayat',
    slug: 'ayat',
    category: 'special_obligatory',
    obligation: 'wajib',
    titles: { en: 'Namaz-e-Ayat', ur: 'نمازِ آیات', ar: 'صلاة الآيات' },
    subtitles: { en: 'Signs prayer', ur: 'آیات کی نماز', ar: 'صلاة الآيات' },
    purpose: {
      en: 'Obligatory when natural signs occur (eclipse, earthquake, etc.).',
      ur: 'قدرتی آیات (سورج/چاند گرہن، زلزلہ وغیرہ) پر واجب۔',
      ar: 'تجب عند الآيات (الكسوف والزلزلة ونحوها).',
    },
    description: {
      en: 'Structure: 2 rakats per sign unit; detailed method for solar/lunar eclipse and tremors.',
      ur: 'ہر آیت پر ۲ رکعت؛ گرہن و زلزلہ کا تفصیلی طریقہ۔',
      ar: 'ركعتان لكل آية؛ تفصيل الكسوف والزلزلة.',
    },
    estimatedMinutes: 15,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['special', 'ayat', 'signs'],
  },
  {
    id: 'namaz_e_mayyit',
    slug: 'mayyit',
    category: 'special_obligatory',
    obligation: 'wajib_kifai',
    titles: { en: 'Namaz-e-Mayyit', ur: 'نمازِ میّت', ar: 'صلاة الميت' },
    subtitles: { en: 'Funeral prayer', ur: 'جنازہ', ar: 'صلاة الجنازة' },
    purpose: {
      en: 'Wajib al-kifai funeral prayer for the deceased Muslim.',
      ur: 'میّت مسلمان پر واجبِ کفائی نماز۔',
      ar: 'صلاة واجبة كفائية على المسلم المتوفى.',
    },
    description: {
      en: 'Five takbirs, duas, and rulings for standing, distance, and ghusl mayyit prerequisites.',
      ur: 'پانچ تکبیریں، دعائیں، کھڑے ہونے اور غسل میّت کے احکام۔',
      ar: 'خمس تكبيرات وأدعية وأحكام الوقوف والغسل.',
    },
    estimatedMinutes: 10,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['special', 'funeral', 'mayyit'],
  },
  {
    id: 'namaz_e_wahshat',
    slug: 'wahshat',
    category: 'special_recommended',
    obligation: 'mustahab',
    titles: { en: 'Namaz-e-Wahshat', ur: 'نمازِ وحشت', ar: 'صلاة الوحشة' },
    subtitles: { en: 'Night of burial', ur: 'دفن کی رات', ar: 'ليلة الدفن' },
    purpose: {
      en: 'Highly recommended on the first night after burial for the deceased.',
      ur: 'میّت کے دفن کی پہلی رات مستحبِ شدید۔',
      ar: 'مستحب شدًا في أول ليلة بعد الدفن للمتوفى.',
    },
    description: {
      en: '2 rakats with specific surahs and dua for easing the deceased\'s loneliness.',
      ur: 'مخصوص سورتوں و دعا کے ساتھ ۲ رکعت — میّت کی تنہائی کے لیے۔',
      ar: 'ركعتان بسور مخصصة ودعاء لرفع وحشة الميت.',
    },
    estimatedMinutes: 8,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['special', 'deceased', 'wahshat'],
  },
  {
    id: 'salat_eid_fitr',
    slug: 'eid-fitr',
    category: 'eid',
    obligation: 'wajib',
    titles: { en: 'Eid ul-Fitr', ur: 'عید الفطر', ar: 'صلاة عيد الفطر' },
    subtitles: { en: 'Fitr festival prayer', ur: 'فطر کی عید', ar: 'عيد الفطر' },
    purpose: {
      en: 'Two wajib rakats on 1st Shawwal with specific rules and khutba after.',
      ur: '۱ شوال کو دو واجب رکعت؛ خاص احکام و خطبہ بعد۔',
      ar: 'ركعتان واجبتان في أول شوال مع خطبة بعدها.',
    },
    description: {
      en: 'Eid Fitr prayer: 5 takbirs in 1st rakat, 4 in 2nd; no adhan/iqamah.',
      ur: 'عید الفطر: پہلی رکعت ۵، دوسری ۴ تکبیر؛ اذان/اقامہ نہیں۔',
      ar: 'عيد الفطر: ٥ تكبيرات في الأولى و٤ في الثانية؛ بلا أذان وإقامة.',
    },
    estimatedMinutes: 12,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['eid', 'fitr', 'festival'],
  },
  {
    id: 'salat_eid_adha',
    slug: 'eid-adha',
    category: 'eid',
    obligation: 'wajib',
    titles: { en: 'Eid ul-Adha', ur: 'عید الاضحیٰ', ar: 'صلاة عيد الأضحى' },
    subtitles: { en: 'Sacrifice festival prayer', ur: 'قربانی کی عید', ar: 'عيد الأضحى' },
    purpose: {
      en: 'Two wajib rakats on 10th Dhul Hijjah.',
      ur: '۱۰ ذوالحجہ کو دو واجب رکعت۔',
      ar: 'ركعتان واجبتان في العاشر من ذي الحجة.',
    },
    description: {
      en: 'Same structure as Eid Fitr; performed before sacrifice when possible.',
      ur: 'عید الفطر جیسا طریقہ؛ ترجیحاً قربانی سے پہلے۔',
      ar: 'مثل عيد الفطر؛ تؤدى قبل الذبح إن أمكن.',
    },
    estimatedMinutes: 12,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['eid', 'adha', 'festival'],
  },
  {
    id: 'salat_jumuah',
    slug: 'jumuah',
    category: 'jumuah',
    obligation: 'conditional',
    titles: { en: 'Salat al-Jumu\'ah', ur: 'نمازِ جمعہ', ar: 'صلاة الجمعة' },
    subtitles: { en: 'Friday congregational', ur: 'جمعہ', ar: 'الجمعة' },
    purpose: {
      en: 'Replaces Dhuhr for eligible men when conditions are met; 2 rakats with khutba.',
      ur: 'شرائط پوری ہوں تو مردوں پر ظہر کی جگہ؛ ۲ رکعت و خطبہ۔',
      ar: 'تقام مقام الظهر للرجال المستوفين للشروط؛ ركعتان وخطبة.',
    },
    description: {
      en: 'Shia Jumu\'ah conditions, adhan/iqamah, 2-rakat method, and khutba etiquette.',
      ur: 'شیا جمعہ کی شرائط، اذان/اقامہ، ۲ رکعت، خطبہ کے آداب۔',
      ar: 'شروط الجمعة عند الشيعة والأذان والركعتان وآداب الخطبة.',
    },
    estimatedMinutes: 15,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['jumuah', 'friday', 'congregation'],
  },
  {
    id: 'salat_ghufayla',
    slug: 'ghufayla',
    category: 'nafl',
    obligation: 'mustahab',
    titles: { en: 'Salat al-Ghufayla', ur: 'نمازِ غفیلہ', ar: 'صلاة الغفيلة' },
    subtitles: { en: 'Between Maghrib & Isha', ur: 'مغرب و عشاء کے درمیان', ar: 'بين المغرب والعشاء' },
    purpose: {
      en: 'Highly recommended 2 rakats between Maghrib and Isha.',
      ur: 'مغرب و عشاء کے درمیان دو مستحب رکعت۔',
      ar: 'ركعتان مستحبتان بين المغرب والعشاء.',
    },
    description: {
      en: 'Includes specific dua between the two sujud of 2nd rakat (Du\'a Ghufayla).',
      ur: 'دوسری رکعت کے دو سجدوں کے درمیان خاص دعا (دعائے غفیلہ)۔',
      ar: 'تشتمل على دعاء خاص بين سجدتي الركعة الثانية.',
    },
    estimatedMinutes: 6,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['nafl', 'ghufayla', 'recommended'],
  },
  {
    id: 'salat_layl',
    slug: 'layl',
    category: 'nafl',
    obligation: 'mustahab',
    titles: { en: 'Salat al-Layl', ur: 'نمازِ شب / تہجد', ar: 'صلاة الليل / التهجد' },
    subtitles: { en: 'Night vigil prayer', ur: 'تہجد', ar: 'التهجد' },
    purpose: {
      en: 'Recommended night prayer — typically 8 rakats + optional + Witr.',
      ur: 'مستحب شب کی نماز — عموماً ۸ رکعت + اختیاری + وتر۔',
      ar: 'صلاة الليل المستحبة — عادة ٨ ركعات + تطوع + وتر.',
    },
    description: {
      en: 'Tahajjud structure, timing after midnight, and virtues narrated from Ahlul Bayt (as).',
      ur: 'تہجد کا ڈھانچہ، آدhi رات کے بعد کا وقت، و فضائلِ آل محمدؑ۔',
      ar: 'هيكل التهجد ووقته بعد منتصف الليل وفضائله عن أهل البيت (ع).',
    },
    estimatedMinutes: 20,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['nafl', 'layl', 'tahajjud', 'night'],
    featured: true,
  },
  {
    id: 'salat_istikhara',
    slug: 'istikhara',
    category: 'nafl',
    obligation: 'mustahab',
    titles: { en: 'Salat al-Istikhara', ur: 'نمازِ استخارہ', ar: 'صلاة الاستخارة' },
    subtitles: { en: 'Seeking guidance', ur: 'رہنمائی طلب', ar: 'طلب الهداية' },
    purpose: {
      en: '2 rakats when seeking Allah\'s guidance in a decision.',
      ur: 'کسی معاملے میں اللہ کی رہنمائی کے لیے ۲ رکعت۔',
      ar: 'ركعتان لطلب هداية الله في أمر.',
    },
    description: {
      en: 'Method, specific dua after prayer, and etiquette for interpreting outcomes.',
      ur: 'طریقہ، نماز کے بعد دعا، اور نتیجہ کے آداب۔',
      ar: 'الطريقة ودعاء ما بعد الصلاة وآداب التوكل.',
    },
    estimatedMinutes: 8,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['nafl', 'istikhara', 'guidance'],
  },
  {
    id: 'nafl_recommended',
    slug: 'nafl-daily',
    category: 'nafl',
    obligation: 'mustahab',
    titles: { en: 'Daily Recommended Nafl', ur: 'روزانہ مستحب نفل', ar: 'النوافل المستحبة اليومية' },
    subtitles: { en: 'Mustahab prayers', ur: 'مستحب نمازیں', ar: 'الصلوات المستحبة' },
    purpose: {
      en: 'Overview of sunnah/mustahab prayers attached to daily wajib salat.',
      ur: 'واجب نمازوں سے منسلک مستحب/سنت نمازوں کا مجموعی تعارف۔',
      ar: 'نبذة عن النوافل المستحبة الملحقة بالصلوات الواجبة.',
    },
    description: {
      en: 'Before Dhuhr, after Dhuhr/Maghrib/Isha, Shaf\' & Witr — with rakat counts.',
      ur: 'ظہر سے پہلے، ظہر/مغرب/عشاء بعد، شفع و وتر — رکعتوں کے ساتھ۔',
      ar: 'قبل الظهر وبعد الظهر/المغرب/العشاء والشفع والوتر.',
    },
    estimatedMinutes: 10,
    hasAudio: false,
    hasGuidedMode: true,
    tags: ['nafl', 'mustahab', 'daily'],
  },
];

export const PRAYER_CATEGORY_ORDER = [
  'obligatory_daily',
  'special_obligatory',
  'special_recommended',
  'eid',
  'jumuah',
  'nafl',
] as const;

export function getCatalogMeta(id: PrayerAcademyMeta['id']): PrayerAcademyMeta {
  const meta = PRAYER_ACADEMY_CATALOG.find((p) => p.id === id);
  if (!meta) throw new Error(`Unknown prayer id: ${id}`);
  return meta;
}
