import type { WorshipGuideMeta } from '../types';

export const WORSHIP_GUIDE_CATALOG: WorshipGuideMeta[] = [
  {
    id: 'wudu_standard',
    slug: 'wudu',
    domain: 'taharah',
    category: 'wudu',
    obligation: 'conditional',
    titles: { en: 'Wudu (Ablution)', ur: 'وضو', ar: 'الوضوء' },
    subtitles: { en: 'Step-by-step taharah', ur: 'مرحلہ وار طہارت', ar: 'الطهارة خطوة بخطوة' },
    purpose: {
      en: 'Purification before salah and other acts of worship',
      ur: 'نماز و عبادت سے پہلے طہارت',
      ar: 'الطهارة قبل الصلاة والعبادة',
    },
    description: {
      en: 'Complete Jafari wudu: niyyah, face, arms, masah of head and feet.',
      ur: 'فقہ جعفریہ کے مطابق مکمل وضو۔',
      ar: 'الوضو الكامل على المذهب الجعفري.',
    },
    estimatedMinutes: 5,
    stepCount: 8,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['wudu', 'taharah', 'daily'],
    featured: true,
  },
  {
    id: 'ghusl_janabat',
    slug: 'ghusl-janabat',
    domain: 'taharah',
    category: 'ghusl',
    obligation: 'wajib',
    titles: { en: 'Ghusl Janabat', ur: 'غسل جنابت', ar: 'غسل الجنابة' },
    subtitles: { en: 'After janabah', ur: 'جنابت کے بعد', ar: 'بعد الجنابة' },
    purpose: {
      en: 'Obligatory bath after sexual intercourse or certain emissions',
      ur: 'جماع یا مخصوص اخروج کے بعد واجب غسل',
      ar: 'الغسل الواجب بعد الجماع أو الاستمناء',
    },
    description: {
      en: 'Tartibi (sequential) method according to Fiqh Jafariya.',
      ur: 'ترتیبی طریقہ — فقہ جعفریہ۔',
      ar: 'الطريقة الترتيبية في الفقه الجعفري.',
    },
    estimatedMinutes: 10,
    stepCount: 5,
    hasAudio: true,
    hasGuidedMode: true,
    prerequisites: ['wudu_standard'],
    tags: ['ghusl', 'janabat'],
    featured: true,
  },
  {
    id: 'ghusl_mayyit',
    slug: 'ghusl-mayyit',
    domain: 'taharah',
    category: 'ghusl',
    obligation: 'wajib_kifai',
    titles: { en: 'Ghusl Mayyit', ur: 'غسل میت', ar: 'غسل الميت' },
    subtitles: { en: 'Washing the deceased', ur: 'میت کو غسل دینا', ar: 'غسل الميت' },
    purpose: {
      en: 'Funeral ghusl — communal obligation on Muslims',
      ur: 'کفن دفن سے پہلے میت کا غسل — واجب کفائی',
      ar: 'غسل الميت — واجب كفائي',
    },
    description: {
      en: 'Rules for washing a Muslim who has passed away.',
      ur: 'فوت شدہ مسلمان کے غسل کے احکام۔',
      ar: 'أحكام غسل المسلم بعد الوفاة.',
    },
    estimatedMinutes: 15,
    stepCount: 6,
    hasAudio: false,
    hasGuidedMode: true,
    tags: ['ghusl', 'mayyit', 'funeral'],
  },
  {
    id: 'ghusl_haiz',
    slug: 'ghusl-haiz',
    domain: 'taharah',
    category: 'ghusl',
    obligation: 'wajib',
    titles: { en: 'Ghusl Hayd', ur: 'غسل حیض', ar: 'غسل الحيض' },
    subtitles: { en: 'After menstruation', ur: 'حیض ختم ہونے پر', ar: 'بعد انقطاع الحيض' },
    purpose: {
      en: 'Obligatory when hayd bleeding ends',
      ur: 'حیض ختم ہونے پر واجب',
      ar: 'واجب عند انقطاع دم الحيض',
    },
    description: {
      en: 'Purification after menstruation before resuming salah.',
      ur: 'حیض کے بعد نماز کے لیے طہارت۔',
      ar: 'الطهارة بعد الحيض لاستئناف الصلاة.',
    },
    estimatedMinutes: 10,
    stepCount: 5,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['ghusl', 'haiz', 'women'],
  },
  {
    id: 'ghusl_nifas',
    slug: 'ghusl-nifas',
    domain: 'taharah',
    category: 'ghusl',
    obligation: 'wajib',
    titles: { en: 'Ghusl Nifas', ur: 'غسل نفاس', ar: 'غسل النفاس' },
    subtitles: { en: 'After childbirth bleeding', ur: 'نفاس ختم ہونے پر', ar: 'بعد النفاس' },
    purpose: {
      en: 'Obligatory when nifas bleeding ends',
      ur: 'نفاس ختم ہونے پر واجب',
      ar: 'واجب عند انقطاع دم النفاس',
    },
    description: {
      en: 'Purification after postpartum bleeding.',
      ur: 'ولادت کے بعد خون بندی ختم ہونے پر غسل۔',
      ar: 'الطهارة بعد انقطاع دم النفاس.',
    },
    estimatedMinutes: 10,
    stepCount: 5,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['ghusl', 'nifas', 'women'],
  },
  {
    id: 'ghusl_jumuah',
    slug: 'ghusl-jumuah',
    domain: 'taharah',
    category: 'ghusl',
    obligation: 'mustahab',
    titles: { en: 'Ghusl Jumu\'ah', ur: 'غسل جمعہ', ar: 'غسل الجمعة' },
    subtitles: { en: 'Recommended before Jumu\'ah', ur: 'جمعہ سے پہلے مستحب', ar: 'مستحب قبل الجمعة' },
    purpose: {
      en: 'Mustahab purification on Friday before Salat al-Jumu\'ah',
      ur: 'جمعہ کی نماز سے پہلے مستحب غسل',
      ar: 'غسل مستحب يوم الجمعة قبل الصلاة',
    },
    description: {
      en: 'Same tartibi method; highly recommended in Shia tradition.',
      ur: 'ترتیبی طریقہ؛ شیا روایت میں بہت مستحب۔',
      ar: 'بالطريقة الترتيبية؛ مستحب في التراث الشيعي.',
    },
    estimatedMinutes: 10,
    stepCount: 5,
    hasAudio: true,
    hasGuidedMode: true,
    tags: ['ghusl', 'jumuah', 'friday'],
  },
  {
    id: 'ghusl_istihada',
    slug: 'ghusl-istihada',
    domain: 'taharah',
    category: 'ghusl',
    obligation: 'conditional',
    titles: { en: 'Ghusl Istihada', ur: 'غسل استحاضہ', ar: 'غسل الاستحاضة' },
    subtitles: { en: 'Irregular bleeding', ur: 'بے قاعدہ خون', ar: 'النزيف غير المعتاد' },
    purpose: {
      en: 'Rules for istihada — when bleeding is not hayd',
      ur: 'استحاضہ کے احکام — جب خون حیض نہ ہو',
      ar: 'أحكام الاستحاضة',
    },
    description: {
      en: 'Includes wudu between prayers when required; ghusl when rules apply.',
      ur: 'ضرورت پر نمازوں کے درمیان وضو؛ جب حکم ہو غسل۔',
      ar: 'يشمل الوضو بين الصلوات والغسل عند الوجوب.',
    },
    estimatedMinutes: 12,
    stepCount: 6,
    hasAudio: false,
    hasGuidedMode: true,
    tags: ['ghusl', 'istihada', 'women'],
  },
  {
    id: 'ghusl_mustahab',
    slug: 'ghusl-mustahab',
    domain: 'taharah',
    category: 'ghusl',
    obligation: 'mustahab',
    titles: { en: 'Mustahab Ghusl', ur: 'غسل مستحب', ar: 'الغسل المستحب' },
    subtitles: { en: 'Recommended baths', ur: 'مستحب غسل', ar: 'الاغسال المستحبة' },
    purpose: {
      en: 'Overview of recommended ghusl occasions',
      ur: 'مستحب غسل کے مواقع',
      ar: 'مناسبات الغسل المستحب',
    },
    description: {
      en: 'Eid, rain, entering Makkah, Laylat al-Qadr, and more.',
      ur: 'عید، بارش، مکہ، شب قدر وغیرہ۔',
      ar: 'العيد، المطر، مكة، ليلة القدر وغيرها.',
    },
    estimatedMinutes: 8,
    stepCount: 4,
    hasAudio: false,
    hasGuidedMode: true,
    tags: ['ghusl', 'mustahab'],
  },
];

export function getCatalogMeta(id: WorshipGuideMeta['id']): WorshipGuideMeta {
  const meta = WORSHIP_GUIDE_CATALOG.find((c) => c.id === id);
  if (!meta) throw new Error(`Unknown worship guide: ${id}`);
  return meta;
}
