import type { NotificationRule } from '../types';

/** Curated intelligent notification rules — offline, context-matched at schedule time. */
export const NOTIFICATION_RULES: NotificationRule[] = [
  // —— Duas ——
  {
    id: 'dua_kumail_thursday',
    category: 'duas',
    titleKey: 'notifications.duas.kumail.title',
    bodyKey: 'notifications.duas.kumail.body',
    priority: 'high',
    dayOfWeek: 4,
    hour: 19,
    payload: { category: 'duas', route: 'DuaReader', routeParams: { duaId: 'dua_kumail' }, duaId: 'dua_kumail' },
  },
  {
    id: 'dua_sabah_morning',
    category: 'duas',
    titleKey: 'notifications.duas.sabah.title',
    bodyKey: 'notifications.duas.sabah.body',
    priority: 'default',
    hour: 6,
    payload: { category: 'duas', route: 'DuaReader', routeParams: { duaId: 'dua_sabah' }, duaId: 'dua_sabah' },
  },
  {
    id: 'dua_tawassul_friday',
    category: 'duas',
    titleKey: 'notifications.duas.tawassul.title',
    bodyKey: 'notifications.duas.tawassul.body',
    priority: 'default',
    dayOfWeek: 5,
    hour: 10,
    payload: { category: 'duas', route: 'DuaReader', routeParams: { duaId: 'dua_tawassul' }, duaId: 'dua_tawassul' },
  },
  {
    id: 'dua_ahad_daily',
    category: 'duas',
    titleKey: 'notifications.duas.ahad.title',
    bodyKey: 'notifications.duas.ahad.body',
    priority: 'default',
    hour: 21,
    payload: { category: 'duas', route: 'DuaReader', routeParams: { duaId: 'dua_ahad' }, duaId: 'dua_ahad' },
  },

  // —— Amaal ——
  {
    id: 'amaal_tasbih_daily',
    category: 'amaal',
    titleKey: 'notifications.amaal.tasbih.title',
    bodyKey: 'notifications.amaal.tasbih.body',
    priority: 'default',
    hour: 9,
    payload: { category: 'amaal', route: 'TasbihCounter' },
  },
  {
    id: 'amaal_salawat_friday',
    category: 'amaal',
    titleKey: 'notifications.amaal.salawat.title',
    bodyKey: 'notifications.amaal.salawat.body',
    priority: 'default',
    dayOfWeek: 5,
    hour: 12,
    payload: { category: 'amaal', route: 'Mafatih' },
  },
  {
    id: 'amaal_qadr_ramadan',
    category: 'amaal',
    titleKey: 'notifications.amaal.qadr.title',
    bodyKey: 'notifications.amaal.qadr.body',
    priority: 'high',
    ramadanOnly: true,
    hour: 22,
    payload: { category: 'amaal', route: 'Duas' },
  },
  {
    id: 'amaal_ghadeer',
    category: 'amaal',
    titleKey: 'notifications.amaal.ghadeer.title',
    bodyKey: 'notifications.amaal.ghadeer.body',
    priority: 'high',
    hijriMonth: 12,
    hijriDay: 18,
    daysBefore: 1,
    payload: { category: 'amaal', route: 'Calendar', eventId: 'ghadeer' },
  },

  // —— Fasting ——
  {
    id: 'fast_monday',
    category: 'fasting',
    titleKey: 'notifications.fasting.monday.title',
    bodyKey: 'notifications.fasting.monday.body',
    priority: 'default',
    dayOfWeek: 1,
    hour: 5,
    payload: { category: 'fasting', route: 'Calendar' },
  },
  {
    id: 'fast_thursday',
    category: 'fasting',
    titleKey: 'notifications.fasting.thursday.title',
    bodyKey: 'notifications.fasting.thursday.body',
    priority: 'default',
    dayOfWeek: 4,
    hour: 5,
    payload: { category: 'fasting', route: 'Calendar' },
  },
  {
    id: 'fast_ashura',
    category: 'fasting',
    titleKey: 'notifications.fasting.ashura.title',
    bodyKey: 'notifications.fasting.ashura.body',
    priority: 'high',
    hijriMonth: 1,
    hijriDay: 10,
    daysBefore: 1,
    payload: { category: 'fasting', route: 'MuharramMode', eventId: 'ashura' },
  },
  {
    id: 'fast_arafah',
    category: 'fasting',
    titleKey: 'notifications.fasting.arafah.title',
    bodyKey: 'notifications.fasting.arafah.body',
    priority: 'high',
    hijriMonth: 12,
    hijriDay: 9,
    daysBefore: 1,
    payload: { category: 'fasting', route: 'Calendar', eventId: 'eid_adha' },
  },
  {
    id: 'fast_ramadan_start',
    category: 'fasting',
    titleKey: 'notifications.fasting.ramadan.title',
    bodyKey: 'notifications.fasting.ramadan.body',
    priority: 'high',
    hijriMonth: 9,
    hijriDay: 1,
    daysBefore: 1,
    payload: { category: 'fasting', route: 'Prayer' },
  },

  // —— Muharram ——
  {
    id: 'muharram_daily',
    category: 'muharram',
    titleKey: 'notifications.muharram.daily.title',
    bodyKey: 'notifications.muharram.daily.body',
    priority: 'high',
    muharramOnly: true,
    hour: 8,
    payload: { category: 'muharram', route: 'MuharramMode' },
  },
  {
    id: 'muharram_ashura_eve',
    category: 'muharram',
    titleKey: 'notifications.muharram.ashuraEve.title',
    bodyKey: 'notifications.muharram.ashuraEve.body',
    priority: 'high',
    hijriMonth: 1,
    hijriDay: 9,
    hour: 20,
    payload: { category: 'muharram', route: 'MuharramMode', eventId: 'ashura' },
  },
  {
    id: 'muharram_arbaeen',
    category: 'muharram',
    titleKey: 'notifications.muharram.arbaeen.title',
    bodyKey: 'notifications.muharram.arbaeen.body',
    priority: 'high',
    hijriMonth: 2,
    hijriDay: 20,
    daysBefore: 1,
    payload: { category: 'muharram', route: 'Calendar', eventId: 'arbaeen' },
  },
];

/** Calendar events with priority >= this get event notifications. */
export const EVENT_NOTIFICATION_MIN_PRIORITY = 7;
