import type { SurahMeta } from '../types';

/** Complete 114 surah index — metadata only; ayah text loaded from bundles. */
export const SURAH_METADATA: SurahMeta[] = [
  { number: 1, nameArabic: 'الفاتحة', nameEnglish: 'Al-Fatiha', nameUrdu: 'الفاتحہ', nameTransliteration: 'Al-Fātiḥah', revelation: 'meccan', ayahCount: 7, juzStart: 1 },
  { number: 2, nameArabic: 'البقرة', nameEnglish: 'Al-Baqarah', nameUrdu: 'البقرہ', nameTransliteration: 'Al-Baqarah', revelation: 'medinan', ayahCount: 286, juzStart: 1 },
  { number: 3, nameArabic: 'آل عمران', nameEnglish: 'Ali Imran', nameUrdu: 'آل عمران', nameTransliteration: 'Āl ʿImrān', revelation: 'medinan', ayahCount: 200, juzStart: 3 },
  { number: 4, nameArabic: 'النساء', nameEnglish: 'An-Nisa', nameUrdu: 'النساء', nameTransliteration: 'An-Nisāʾ', revelation: 'medinan', ayahCount: 176, juzStart: 4 },
  { number: 5, nameArabic: 'المائدة', nameEnglish: 'Al-Maidah', nameUrdu: 'المائدہ', nameTransliteration: 'Al-Māʾidah', revelation: 'medinan', ayahCount: 120, juzStart: 6 },
  { number: 6, nameArabic: 'الأنعام', nameEnglish: 'Al-Anam', nameUrdu: 'الانعام', nameTransliteration: 'Al-Anʿām', revelation: 'meccan', ayahCount: 165, juzStart: 7 },
  { number: 7, nameArabic: 'الأعراف', nameEnglish: 'Al-Araf', nameUrdu: 'الاعراف', nameTransliteration: 'Al-Aʿrāf', revelation: 'meccan', ayahCount: 206, juzStart: 8 },
  { number: 8, nameArabic: 'الأنفال', nameEnglish: 'Al-Anfal', nameUrdu: 'الانفال', nameTransliteration: 'Al-Anfāl', revelation: 'medinan', ayahCount: 75, juzStart: 9 },
  { number: 9, nameArabic: 'التوبة', nameEnglish: 'At-Tawbah', nameUrdu: 'التوبہ', nameTransliteration: 'At-Tawbah', revelation: 'medinan', ayahCount: 129, juzStart: 10 },
  { number: 10, nameArabic: 'يونس', nameEnglish: 'Yunus', nameUrdu: 'یونس', nameTransliteration: 'Yūnus', revelation: 'meccan', ayahCount: 109, juzStart: 11 },
  { number: 11, nameArabic: 'هود', nameEnglish: 'Hud', nameUrdu: 'ہود', nameTransliteration: 'Hūd', revelation: 'meccan', ayahCount: 123, juzStart: 11 },
  { number: 12, nameArabic: 'يوسف', nameEnglish: 'Yusuf', nameUrdu: 'یوسف', nameTransliteration: 'Yūsuf', revelation: 'meccan', ayahCount: 111, juzStart: 12 },
  { number: 13, nameArabic: 'الرعد', nameEnglish: 'Ar-Rad', nameUrdu: 'الرعد', nameTransliteration: 'Ar-Raʿd', revelation: 'medinan', ayahCount: 43, juzStart: 13 },
  { number: 14, nameArabic: 'إبراهيم', nameEnglish: 'Ibrahim', nameUrdu: 'ابراہیم', nameTransliteration: 'Ibrāhīm', revelation: 'meccan', ayahCount: 52, juzStart: 13 },
  { number: 15, nameArabic: 'الحجر', nameEnglish: 'Al-Hijr', nameUrdu: 'الحجر', nameTransliteration: 'Al-Ḥijr', revelation: 'meccan', ayahCount: 99, juzStart: 14 },
  { number: 16, nameArabic: 'النحل', nameEnglish: 'An-Nahl', nameUrdu: 'النحل', nameTransliteration: 'An-Naḥl', revelation: 'meccan', ayahCount: 128, juzStart: 14 },
  { number: 17, nameArabic: 'الإسراء', nameEnglish: 'Al-Isra', nameUrdu: 'الاسراء', nameTransliteration: 'Al-Isrāʾ', revelation: 'meccan', ayahCount: 111, juzStart: 15 },
  { number: 18, nameArabic: 'الكهف', nameEnglish: 'Al-Kahf', nameUrdu: 'الکہف', nameTransliteration: 'Al-Kahf', revelation: 'meccan', ayahCount: 110, juzStart: 15 },
  { number: 19, nameArabic: 'مريم', nameEnglish: 'Maryam', nameUrdu: 'مریم', nameTransliteration: 'Maryam', revelation: 'meccan', ayahCount: 98, juzStart: 16 },
  { number: 20, nameArabic: 'طه', nameEnglish: 'Ta-Ha', nameUrdu: 'طہ', nameTransliteration: 'Ṭā-Hā', revelation: 'meccan', ayahCount: 135, juzStart: 16 },
  { number: 21, nameArabic: 'الأنبياء', nameEnglish: 'Al-Anbiya', nameUrdu: 'الانبیاء', nameTransliteration: 'Al-Anbiyāʾ', revelation: 'meccan', ayahCount: 112, juzStart: 17 },
  { number: 22, nameArabic: 'الحج', nameEnglish: 'Al-Hajj', nameUrdu: 'الحج', nameTransliteration: 'Al-Ḥajj', revelation: 'medinan', ayahCount: 78, juzStart: 17 },
  { number: 23, nameArabic: 'المؤمنون', nameEnglish: 'Al-Muminun', nameUrdu: 'المؤمنون', nameTransliteration: 'Al-Muʾminūn', revelation: 'meccan', ayahCount: 118, juzStart: 18 },
  { number: 24, nameArabic: 'النور', nameEnglish: 'An-Nur', nameUrdu: 'النور', nameTransliteration: 'An-Nūr', revelation: 'medinan', ayahCount: 64, juzStart: 18 },
  { number: 25, nameArabic: 'الفرقان', nameEnglish: 'Al-Furqan', nameUrdu: 'الفرقان', nameTransliteration: 'Al-Furqān', revelation: 'meccan', ayahCount: 77, juzStart: 18 },
  { number: 26, nameArabic: 'الشعراء', nameEnglish: 'Ash-Shuara', nameUrdu: 'الشعراء', nameTransliteration: 'Ash-Shuʿarāʾ', revelation: 'meccan', ayahCount: 227, juzStart: 19 },
  { number: 27, nameArabic: 'النمل', nameEnglish: 'An-Naml', nameUrdu: 'النمل', nameTransliteration: 'An-Naml', revelation: 'meccan', ayahCount: 93, juzStart: 19 },
  { number: 28, nameArabic: 'القصص', nameEnglish: 'Al-Qasas', nameUrdu: 'القصص', nameTransliteration: 'Al-Qaṣaṣ', revelation: 'meccan', ayahCount: 88, juzStart: 20 },
  { number: 29, nameArabic: 'العنكبوت', nameEnglish: 'Al-Ankabut', nameUrdu: 'العنکبوت', nameTransliteration: 'Al-ʿAnkabūt', revelation: 'meccan', ayahCount: 69, juzStart: 20 },
  { number: 30, nameArabic: 'الروم', nameEnglish: 'Ar-Rum', nameUrdu: 'الروم', nameTransliteration: 'Ar-Rūm', revelation: 'meccan', ayahCount: 60, juzStart: 21 },
  { number: 31, nameArabic: 'لقمان', nameEnglish: 'Luqman', nameUrdu: 'لقمان', nameTransliteration: 'Luqmān', revelation: 'meccan', ayahCount: 34, juzStart: 21 },
  { number: 32, nameArabic: 'السجدة', nameEnglish: 'As-Sajdah', nameUrdu: 'السجدہ', nameTransliteration: 'As-Sajdah', revelation: 'meccan', ayahCount: 30, juzStart: 21 },
  { number: 33, nameArabic: 'الأحزاب', nameEnglish: 'Al-Ahzab', nameUrdu: 'الاحزاب', nameTransliteration: 'Al-Aḥzāb', revelation: 'medinan', ayahCount: 73, juzStart: 21 },
  { number: 34, nameArabic: 'سبإ', nameEnglish: 'Saba', nameUrdu: 'سبا', nameTransliteration: 'Sabaʾ', revelation: 'meccan', ayahCount: 54, juzStart: 22 },
  { number: 35, nameArabic: 'فاطر', nameEnglish: 'Fatir', nameUrdu: 'فاطر', nameTransliteration: 'Fāṭir', revelation: 'meccan', ayahCount: 45, juzStart: 22 },
  { number: 36, nameArabic: 'يس', nameEnglish: 'Ya-Sin', nameUrdu: 'یٰسٓ', nameTransliteration: 'Yā-Sīn', revelation: 'meccan', ayahCount: 83, juzStart: 22 },
  { number: 37, nameArabic: 'الصافات', nameEnglish: 'As-Saffat', nameUrdu: 'الصافات', nameTransliteration: 'Aṣ-Ṣāffāt', revelation: 'meccan', ayahCount: 182, juzStart: 23 },
  { number: 38, nameArabic: 'ص', nameEnglish: 'Sad', nameUrdu: 'ص', nameTransliteration: 'Ṣād', revelation: 'meccan', ayahCount: 88, juzStart: 23 },
  { number: 39, nameArabic: 'الزمر', nameEnglish: 'Az-Zumar', nameUrdu: 'الزمر', nameTransliteration: 'Az-Zumar', revelation: 'meccan', ayahCount: 75, juzStart: 23 },
  { number: 40, nameArabic: 'غافر', nameEnglish: 'Ghafir', nameUrdu: 'غافر', nameTransliteration: 'Ghāfir', revelation: 'meccan', ayahCount: 85, juzStart: 24 },
  { number: 41, nameArabic: 'فصلت', nameEnglish: 'Fussilat', nameUrdu: 'فصلت', nameTransliteration: 'Fuṣṣilat', revelation: 'meccan', ayahCount: 54, juzStart: 24 },
  { number: 42, nameArabic: 'الشورى', nameEnglish: 'Ash-Shura', nameUrdu: 'الشوری', nameTransliteration: 'Ash-Shūrā', revelation: 'meccan', ayahCount: 53, juzStart: 25 },
  { number: 43, nameArabic: 'الزخرف', nameEnglish: 'Az-Zukhruf', nameUrdu: 'الزخرف', nameTransliteration: 'Az-Zukhruf', revelation: 'meccan', ayahCount: 89, juzStart: 25 },
  { number: 44, nameArabic: 'الدخان', nameEnglish: 'Ad-Dukhan', nameUrdu: 'الدخان', nameTransliteration: 'Ad-Dukhān', revelation: 'meccan', ayahCount: 59, juzStart: 25 },
  { number: 45, nameArabic: 'الجاثية', nameEnglish: 'Al-Jathiyah', nameUrdu: 'الجاثیہ', nameTransliteration: 'Al-Jāthiyah', revelation: 'meccan', ayahCount: 37, juzStart: 25 },
  { number: 46, nameArabic: 'الأحقاف', nameEnglish: 'Al-Ahqaf', nameUrdu: 'الاحقاف', nameTransliteration: 'Al-Aḥqāf', revelation: 'meccan', ayahCount: 35, juzStart: 26 },
  { number: 47, nameArabic: 'محمد', nameEnglish: 'Muhammad', nameUrdu: 'محمد', nameTransliteration: 'Muḥammad', revelation: 'medinan', ayahCount: 38, juzStart: 26 },
  { number: 48, nameArabic: 'الفتح', nameEnglish: 'Al-Fath', nameUrdu: 'الفتح', nameTransliteration: 'Al-Fatḥ', revelation: 'medinan', ayahCount: 29, juzStart: 26 },
  { number: 49, nameArabic: 'الحجرات', nameEnglish: 'Al-Hujurat', nameUrdu: 'الحجرات', nameTransliteration: 'Al-Ḥujurāt', revelation: 'medinan', ayahCount: 18, juzStart: 26 },
  { number: 50, nameArabic: 'ق', nameEnglish: 'Qaf', nameUrdu: 'ق', nameTransliteration: 'Qāf', revelation: 'meccan', ayahCount: 45, juzStart: 26 },
  { number: 51, nameArabic: 'الذاريات', nameEnglish: 'Adh-Dhariyat', nameUrdu: 'الذاریات', nameTransliteration: 'Adh-Dhāriyāt', revelation: 'meccan', ayahCount: 60, juzStart: 26 },
  { number: 52, nameArabic: 'الطور', nameEnglish: 'At-Tur', nameUrdu: 'الطور', nameTransliteration: 'Aṭ-Ṭūr', revelation: 'meccan', ayahCount: 49, juzStart: 27 },
  { number: 53, nameArabic: 'النجم', nameEnglish: 'An-Najm', nameUrdu: 'النجم', nameTransliteration: 'An-Najm', revelation: 'meccan', ayahCount: 62, juzStart: 27 },
  { number: 54, nameArabic: 'القمر', nameEnglish: 'Al-Qamar', nameUrdu: 'القمر', nameTransliteration: 'Al-Qamar', revelation: 'meccan', ayahCount: 55, juzStart: 27 },
  { number: 55, nameArabic: 'الرحمن', nameEnglish: 'Ar-Rahman', nameUrdu: 'الرحمن', nameTransliteration: 'Ar-Raḥmān', revelation: 'medinan', ayahCount: 78, juzStart: 27 },
  { number: 56, nameArabic: 'الواقعة', nameEnglish: 'Al-Waqiah', nameUrdu: 'الواقعہ', nameTransliteration: 'Al-Wāqiʿah', revelation: 'meccan', ayahCount: 96, juzStart: 27 },
  { number: 57, nameArabic: 'الحديد', nameEnglish: 'Al-Hadid', nameUrdu: 'الحدید', nameTransliteration: 'Al-Ḥadīd', revelation: 'medinan', ayahCount: 29, juzStart: 27 },
  { number: 58, nameArabic: 'المجادلة', nameEnglish: 'Al-Mujadila', nameUrdu: 'المجادلہ', nameTransliteration: 'Al-Mujādilah', revelation: 'medinan', ayahCount: 22, juzStart: 28 },
  { number: 59, nameArabic: 'الحشر', nameEnglish: 'Al-Hashr', nameUrdu: 'الحشر', nameTransliteration: 'Al-Ḥashr', revelation: 'medinan', ayahCount: 24, juzStart: 28 },
  { number: 60, nameArabic: 'الممتحنة', nameEnglish: 'Al-Mumtahanah', nameUrdu: 'الممتحنہ', nameTransliteration: 'Al-Mumtaḥanah', revelation: 'medinan', ayahCount: 13, juzStart: 28 },
  { number: 61, nameArabic: 'الصف', nameEnglish: 'As-Saff', nameUrdu: 'الصف', nameTransliteration: 'Aṣ-Ṣaff', revelation: 'medinan', ayahCount: 14, juzStart: 28 },
  { number: 62, nameArabic: 'الجمعة', nameEnglish: 'Al-Jumuah', nameUrdu: 'الجمعہ', nameTransliteration: 'Al-Jumuʿah', revelation: 'medinan', ayahCount: 11, juzStart: 28 },
  { number: 63, nameArabic: 'المنافقون', nameEnglish: 'Al-Munafiqun', nameUrdu: 'المنافقون', nameTransliteration: 'Al-Munāfiqūn', revelation: 'medinan', ayahCount: 11, juzStart: 28 },
  { number: 64, nameArabic: 'التغابن', nameEnglish: 'At-Taghabun', nameUrdu: 'التغابن', nameTransliteration: 'At-Taghābun', revelation: 'medinan', ayahCount: 18, juzStart: 28 },
  { number: 65, nameArabic: 'الطلاق', nameEnglish: 'At-Talaq', nameUrdu: 'الطلاق', nameTransliteration: 'Aṭ-Ṭalāq', revelation: 'medinan', ayahCount: 12, juzStart: 28 },
  { number: 66, nameArabic: 'التحريم', nameEnglish: 'At-Tahrim', nameUrdu: 'التحریم', nameTransliteration: 'At-Taḥrīm', revelation: 'medinan', ayahCount: 12, juzStart: 28 },
  { number: 67, nameArabic: 'الملك', nameEnglish: 'Al-Mulk', nameUrdu: 'الملک', nameTransliteration: 'Al-Mulk', revelation: 'meccan', ayahCount: 30, juzStart: 29 },
  { number: 68, nameArabic: 'القلم', nameEnglish: 'Al-Qalam', nameUrdu: 'القلم', nameTransliteration: 'Al-Qalam', revelation: 'meccan', ayahCount: 52, juzStart: 29 },
  { number: 69, nameArabic: 'الحاقة', nameEnglish: 'Al-Haqqah', nameUrdu: 'الحاقہ', nameTransliteration: 'Al-Ḥāqqah', revelation: 'meccan', ayahCount: 52, juzStart: 29 },
  { number: 70, nameArabic: 'المعارج', nameEnglish: 'Al-Maarij', nameUrdu: 'المعارج', nameTransliteration: 'Al-Maʿārij', revelation: 'meccan', ayahCount: 44, juzStart: 29 },
  { number: 71, nameArabic: 'نوح', nameEnglish: 'Nuh', nameUrdu: 'نوح', nameTransliteration: 'Nūḥ', revelation: 'meccan', ayahCount: 28, juzStart: 29 },
  { number: 72, nameArabic: 'الجن', nameEnglish: 'Al-Jinn', nameUrdu: 'الجن', nameTransliteration: 'Al-Jinn', revelation: 'meccan', ayahCount: 28, juzStart: 29 },
  { number: 73, nameArabic: 'المزمل', nameEnglish: 'Al-Muzzammil', nameUrdu: 'المزمل', nameTransliteration: 'Al-Muzzammil', revelation: 'meccan', ayahCount: 20, juzStart: 29 },
  { number: 74, nameArabic: 'المدثر', nameEnglish: 'Al-Muddaththir', nameUrdu: 'المدثر', nameTransliteration: 'Al-Muddaththir', revelation: 'meccan', ayahCount: 56, juzStart: 29 },
  { number: 75, nameArabic: 'القيامة', nameEnglish: 'Al-Qiyamah', nameUrdu: 'القیامہ', nameTransliteration: 'Al-Qiyāmah', revelation: 'meccan', ayahCount: 40, juzStart: 29 },
  { number: 76, nameArabic: 'الإنسان', nameEnglish: 'Al-Insan', nameUrdu: 'الانسان', nameTransliteration: 'Al-Insān', revelation: 'medinan', ayahCount: 31, juzStart: 29 },
  { number: 77, nameArabic: 'المرسلات', nameEnglish: 'Al-Mursalat', nameUrdu: 'المرسلات', nameTransliteration: 'Al-Mursalāt', revelation: 'meccan', ayahCount: 50, juzStart: 29 },
  { number: 78, nameArabic: 'النبإ', nameEnglish: 'An-Naba', nameUrdu: 'النبأ', nameTransliteration: 'An-Nabaʾ', revelation: 'meccan', ayahCount: 40, juzStart: 30 },
  { number: 79, nameArabic: 'النازعات', nameEnglish: 'An-Naziat', nameUrdu: 'النازعات', nameTransliteration: 'An-Nāziʿāt', revelation: 'meccan', ayahCount: 46, juzStart: 30 },
  { number: 80, nameArabic: 'عبس', nameEnglish: 'Abasa', nameUrdu: 'عبس', nameTransliteration: 'ʿAbasa', revelation: 'meccan', ayahCount: 42, juzStart: 30 },
  { number: 81, nameArabic: 'التكوير', nameEnglish: 'At-Takwir', nameUrdu: 'التکویر', nameTransliteration: 'At-Takwīr', revelation: 'meccan', ayahCount: 29, juzStart: 30 },
  { number: 82, nameArabic: 'الانفطار', nameEnglish: 'Al-Infitar', nameUrdu: 'الانفطار', nameTransliteration: 'Al-Infiṭār', revelation: 'meccan', ayahCount: 19, juzStart: 30 },
  { number: 83, nameArabic: 'المطففين', nameEnglish: 'Al-Mutaffifin', nameUrdu: 'المطففین', nameTransliteration: 'Al-Muṭaffifīn', revelation: 'meccan', ayahCount: 36, juzStart: 30 },
  { number: 84, nameArabic: 'الانشقاق', nameEnglish: 'Al-Inshiqaq', nameUrdu: 'الانشقاق', nameTransliteration: 'Al-Inshiqāq', revelation: 'meccan', ayahCount: 25, juzStart: 30 },
  { number: 85, nameArabic: 'البروج', nameEnglish: 'Al-Buruj', nameUrdu: 'البروج', nameTransliteration: 'Al-Burūj', revelation: 'meccan', ayahCount: 22, juzStart: 30 },
  { number: 86, nameArabic: 'الطارق', nameEnglish: 'At-Tariq', nameUrdu: 'الطارق', nameTransliteration: 'Aṭ-Ṭāriq', revelation: 'meccan', ayahCount: 17, juzStart: 30 },
  { number: 87, nameArabic: 'الأعلى', nameEnglish: 'Al-Ala', nameUrdu: 'الاعلی', nameTransliteration: 'Al-Aʿlā', revelation: 'meccan', ayahCount: 19, juzStart: 30 },
  { number: 88, nameArabic: 'الغاشية', nameEnglish: 'Al-Ghashiyah', nameUrdu: 'الغاشیہ', nameTransliteration: 'Al-Ghāshiyah', revelation: 'meccan', ayahCount: 26, juzStart: 30 },
  { number: 89, nameArabic: 'الفجر', nameEnglish: 'Al-Fajr', nameUrdu: 'الفجر', nameTransliteration: 'Al-Fajr', revelation: 'meccan', ayahCount: 30, juzStart: 30 },
  { number: 90, nameArabic: 'البلد', nameEnglish: 'Al-Balad', nameUrdu: 'البلد', nameTransliteration: 'Al-Balad', revelation: 'meccan', ayahCount: 20, juzStart: 30 },
  { number: 91, nameArabic: 'الشمس', nameEnglish: 'Ash-Shams', nameUrdu: 'الشمس', nameTransliteration: 'Ash-Shams', revelation: 'meccan', ayahCount: 15, juzStart: 30 },
  { number: 92, nameArabic: 'الليل', nameEnglish: 'Al-Layl', nameUrdu: 'الیل', nameTransliteration: 'Al-Layl', revelation: 'meccan', ayahCount: 21, juzStart: 30 },
  { number: 93, nameArabic: 'الضحى', nameEnglish: 'Ad-Duha', nameUrdu: 'الضحی', nameTransliteration: 'Aḍ-Ḍuḥā', revelation: 'meccan', ayahCount: 11, juzStart: 30 },
  { number: 94, nameArabic: 'الشرح', nameEnglish: 'Ash-Sharh', nameUrdu: 'الشرح', nameTransliteration: 'Ash-Sharḥ', revelation: 'meccan', ayahCount: 8, juzStart: 30 },
  { number: 95, nameArabic: 'التين', nameEnglish: 'At-Tin', nameUrdu: 'التین', nameTransliteration: 'At-Tīn', revelation: 'meccan', ayahCount: 8, juzStart: 30 },
  { number: 96, nameArabic: 'العلق', nameEnglish: 'Al-Alaq', nameUrdu: 'العلق', nameTransliteration: 'Al-ʿAlaq', revelation: 'meccan', ayahCount: 19, juzStart: 30 },
  { number: 97, nameArabic: 'القدر', nameEnglish: 'Al-Qadr', nameUrdu: 'القدر', nameTransliteration: 'Al-Qadr', revelation: 'meccan', ayahCount: 5, juzStart: 30 },
  { number: 98, nameArabic: 'البينة', nameEnglish: 'Al-Bayyinah', nameUrdu: 'البینہ', nameTransliteration: 'Al-Bayyinah', revelation: 'medinan', ayahCount: 8, juzStart: 30 },
  { number: 99, nameArabic: 'الزلزلة', nameEnglish: 'Az-Zalzalah', nameUrdu: 'الزلزلہ', nameTransliteration: 'Az-Zalzalah', revelation: 'medinan', ayahCount: 8, juzStart: 30 },
  { number: 100, nameArabic: 'العاديات', nameEnglish: 'Al-Adiyat', nameUrdu: 'العاديات', nameTransliteration: 'Al-ʿĀdiyāt', revelation: 'meccan', ayahCount: 11, juzStart: 30 },
  { number: 101, nameArabic: 'القارعة', nameEnglish: 'Al-Qariah', nameUrdu: 'القارعہ', nameTransliteration: 'Al-Qāriʿah', revelation: 'meccan', ayahCount: 11, juzStart: 30 },
  { number: 102, nameArabic: 'التكاثر', nameEnglish: 'At-Takathur', nameUrdu: 'التکاثر', nameTransliteration: 'At-Takāthur', revelation: 'meccan', ayahCount: 8, juzStart: 30 },
  { number: 103, nameArabic: 'العصر', nameEnglish: 'Al-Asr', nameUrdu: 'العصر', nameTransliteration: 'Al-ʿAṣr', revelation: 'meccan', ayahCount: 3, juzStart: 30 },
  { number: 104, nameArabic: 'الهمزة', nameEnglish: 'Al-Humazah', nameUrdu: 'الہمزہ', nameTransliteration: 'Al-Humazah', revelation: 'meccan', ayahCount: 9, juzStart: 30 },
  { number: 105, nameArabic: 'الفيل', nameEnglish: 'Al-Fil', nameUrdu: 'الفیل', nameTransliteration: 'Al-Fīl', revelation: 'meccan', ayahCount: 5, juzStart: 30 },
  { number: 106, nameArabic: 'قريش', nameEnglish: 'Quraysh', nameUrdu: 'قریش', nameTransliteration: 'Quraysh', revelation: 'meccan', ayahCount: 4, juzStart: 30 },
  { number: 107, nameArabic: 'الماعون', nameEnglish: 'Al-Maun', nameUrdu: 'الماعون', nameTransliteration: 'Al-Māʿūn', revelation: 'meccan', ayahCount: 7, juzStart: 30 },
  { number: 108, nameArabic: 'الكوثر', nameEnglish: 'Al-Kawthar', nameUrdu: 'الکوثر', nameTransliteration: 'Al-Kawthar', revelation: 'meccan', ayahCount: 3, juzStart: 30 },
  { number: 109, nameArabic: 'الكافرون', nameEnglish: 'Al-Kafirun', nameUrdu: 'الکافرون', nameTransliteration: 'Al-Kāfirūn', revelation: 'meccan', ayahCount: 6, juzStart: 30 },
  { number: 110, nameArabic: 'النصر', nameEnglish: 'An-Nasr', nameUrdu: 'النصر', nameTransliteration: 'An-Naṣr', revelation: 'medinan', ayahCount: 3, juzStart: 30 },
  { number: 111, nameArabic: 'المسد', nameEnglish: 'Al-Masad', nameUrdu: 'المسد', nameTransliteration: 'Al-Masad', revelation: 'meccan', ayahCount: 5, juzStart: 30 },
  { number: 112, nameArabic: 'الإخلاص', nameEnglish: 'Al-Ikhlas', nameUrdu: 'الاخلاص', nameTransliteration: 'Al-Ikhlāṣ', revelation: 'meccan', ayahCount: 4, juzStart: 30 },
  { number: 113, nameArabic: 'الفلق', nameEnglish: 'Al-Falaq', nameUrdu: 'الفلق', nameTransliteration: 'Al-Falaq', revelation: 'meccan', ayahCount: 5, juzStart: 30 },
  { number: 114, nameArabic: 'الناس', nameEnglish: 'An-Nas', nameUrdu: 'الناس', nameTransliteration: 'An-Nās', revelation: 'meccan', ayahCount: 6, juzStart: 30 },
];

export function getSurahMeta(number: number): SurahMeta | undefined {
  return SURAH_METADATA.find((s) => s.number === number);
}

export const RECITERS = [
  { id: 'al_afasy', nameKey: 'quran.reciters.alAfasy' },
  { id: 'abdul_basit', nameKey: 'quran.reciters.abdulBasit' },
  { id: 'minshawi', nameKey: 'quran.reciters.minshawi' },
] as const;
