import type { WorshipPose } from '../types';

export interface PoseGeometry {
  /** Torso rotation degrees (forward bend) */
  torsoRotate: number;
  /** Whole figure translate Y */
  figureY: number;
  /** Head offset Y from default */
  headY: number;
  /** Left arm: [shoulderRot, extendY] */
  leftArm: [number, number];
  rightArm: [number, number];
  /** Legs: sitting vs standing */
  sitting: boolean;
  /** Show water overlay zones */
  waterZones: Array<'face' | 'arm_r' | 'arm_l' | 'head' | 'feet' | 'immersion'>;
  /** Hands raised (qunoot/takbir) */
  handsRaised: boolean;
  /** Prostration — figure horizontal */
  prostration: boolean;
}

export const POSE_GEOMETRY: Record<WorshipPose, PoseGeometry> = {
  standing_neutral: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [0, 0],
    rightArm: [0, 0],
    sitting: false,
    waterZones: [],
    handsRaised: false,
    prostration: false,
  },
  takbir: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [-145, -8],
    rightArm: [145, -8],
    sitting: false,
    waterZones: [],
    handsRaised: true,
    prostration: false,
  },
  standing_qiyam: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [8, 4],
    rightArm: [-8, 4],
    sitting: false,
    waterZones: [],
    handsRaised: false,
    prostration: false,
  },
  qunoot_hands_raised: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [-130, -12],
    rightArm: [130, -12],
    sitting: false,
    waterZones: [],
    handsRaised: true,
    prostration: false,
  },
  ruku: {
    torsoRotate: 55,
    figureY: 18,
    headY: 8,
    leftArm: [20, 20],
    rightArm: [-20, 20],
    sitting: false,
    waterZones: [],
    handsRaised: false,
    prostration: false,
  },
  sujud: {
    torsoRotate: 88,
    figureY: 42,
    headY: 28,
    leftArm: [70, 8],
    rightArm: [-70, 8],
    sitting: false,
    waterZones: [],
    handsRaised: false,
    prostration: true,
  },
  jalsa: {
    torsoRotate: 0,
    figureY: 24,
    headY: 4,
    leftArm: [0, 8],
    rightArm: [0, 8],
    sitting: true,
    waterZones: [],
    handsRaised: false,
    prostration: false,
  },
  tashahhud_sitting: {
    torsoRotate: 0,
    figureY: 26,
    headY: 2,
    leftArm: [0, 6],
    rightArm: [0, 6],
    sitting: true,
    waterZones: [],
    handsRaised: false,
    prostration: false,
  },
  completion_dhikr: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [0, 0],
    rightArm: [0, 0],
    sitting: false,
    waterZones: [],
    handsRaised: false,
    prostration: false,
  },
  wash_hands: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [-30, -10],
    rightArm: [30, -10],
    sitting: false,
    waterZones: [],
    handsRaised: false,
    prostration: false,
  },
  wash_face: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [-40, -18],
    rightArm: [40, -18],
    sitting: false,
    waterZones: ['face'],
    handsRaised: false,
    prostration: false,
  },
  wash_arm_right: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [0, 4],
    rightArm: [-90, -6],
    sitting: false,
    waterZones: ['arm_r'],
    handsRaised: false,
    prostration: false,
  },
  wash_arm_left: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [90, -6],
    rightArm: [0, 4],
    sitting: false,
    waterZones: ['arm_l'],
    handsRaised: false,
    prostration: false,
  },
  masah_head: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [-60, -22],
    rightArm: [60, -22],
    sitting: false,
    waterZones: ['head'],
    handsRaised: false,
    prostration: false,
  },
  masah_feet: {
    torsoRotate: 15,
    figureY: 8,
    headY: 4,
    leftArm: [0, 12],
    rightArm: [0, 12],
    sitting: false,
    waterZones: ['feet'],
    handsRaised: false,
    prostration: false,
  },
  ghusl_niyyah: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [0, 0],
    rightArm: [0, 0],
    sitting: false,
    waterZones: [],
    handsRaised: false,
    prostration: false,
  },
  ghusl_head: {
    torsoRotate: 0,
    figureY: 0,
    headY: 0,
    leftArm: [-50, -20],
    rightArm: [50, -20],
    sitting: false,
    waterZones: ['head', 'face'],
    handsRaised: false,
    prostration: false,
  },
  ghusl_right: {
    torsoRotate: -8,
    figureY: 0,
    headY: 0,
    leftArm: [0, 0],
    rightArm: [-20, 0],
    sitting: false,
    waterZones: ['arm_r'],
    handsRaised: false,
    prostration: false,
  },
  ghusl_left: {
    torsoRotate: 8,
    figureY: 0,
    headY: 0,
    leftArm: [20, 0],
    rightArm: [0, 0],
    sitting: false,
    waterZones: ['arm_l'],
    handsRaised: false,
    prostration: false,
  },
  ghusl_immersion: {
    torsoRotate: 0,
    figureY: 10,
    headY: 0,
    leftArm: [0, 0],
    rightArm: [0, 0],
    sitting: false,
    waterZones: ['immersion'],
    handsRaised: false,
    prostration: false,
  },
};
