import type { NahjulCategory, NahjulId } from '../types';

export function nahjulId(category: NahjulCategory, number: number): NahjulId {
  return `nb_${category}_${String(number).padStart(3, '0')}` as NahjulId;
}

export type NahjulLocaleEntry = {
  category: NahjulCategory;
  number: number;
  slug: string;
  en: string;
  ur: string;
  ar: string;
  subtitleEn: string;
  subtitleUr: string;
  excerptEn: string;
  excerptUr: string;
  themes: string[];
  minutes: number;
  sections: number;
};

const SERMONS: NahjulLocaleEntry[] = [
  { category: 'sermon', number: 1, slug: 'creation-of-world', en: 'About the Creation of the World', ur: 'تخلیقِ کائنات', ar: 'في خلق العالم', subtitleEn: "On Allah's wisdom in creation", subtitleUr: 'اللہ کی حکمتِ تخلیق', excerptEn: 'Praise be to Allah who spread out the earth and set up mountains...', excerptUr: 'حمد ہے اللہ کی جس نے زمین بچھائی...', themes: ['creation', 'wisdom'], minutes: 15, sections: 4 },
  { category: 'sermon', number: 2, slug: 'muttaqeen', en: 'About the Pious (Muttaqeen)', ur: 'متقین', ar: 'في المتقين', subtitleEn: 'Qualities of the God-fearing', subtitleUr: 'پرہیزگاروں کی صفات', excerptEn: 'They are the trustees of Allah on His earth and callers to His religion...', excerptUr: 'وہ اللہ کے نائب ہیں زمین پر...', themes: ['piety', 'character'], minutes: 12, sections: 3 },
  { category: 'sermon', number: 3, slug: 'ash-shiqshiqiyyah', en: 'Al-Shiqshiqiyyah', ur: 'الشقشیقیہ', ar: 'الشقشقية', subtitleEn: 'The famous sermon on caliphate', subtitleUr: 'خلافت پر مشہور خطبہ', excerptEn: 'By Allah, the son of Abu Quhafah (Abu Bakr) dressed himself with it...', excerptUr: 'قسم ہے اللہ کی، ابنِ ابی قحافہ نے...', themes: ['history', 'caliphate'], minutes: 10, sections: 3 },
  { category: 'sermon', number: 4, slug: 'about-amir-al-muminin', en: "About Amir al-Mu'minin", ur: 'امیرالمومنین کے بارے میں', ar: 'في أمير المؤمنين', subtitleEn: 'On his own station', subtitleUr: 'اپنے مقام پر', excerptEn: 'I am the brother of the Messenger of Allah and his successor...', excerptUr: 'میں رسول اللہؐ کا بھائی اور وصی ہوں...', themes: ['wilayah', 'leadership'], minutes: 8, sections: 2 },
  { category: 'sermon', number: 5, slug: 'about-usman', en: 'About the Murder of Uthman', ur: 'عثمانؓ کے قتل پر', ar: 'في قتل عثمان', subtitleEn: 'On the tragedy of Uthman', subtitleUr: 'عثمانؓ کی شہادت', excerptEn: 'Then matters turned as they did, and the people divided...', excerptUr: 'پھر معاملات بدل گئے...', themes: ['history', 'justice'], minutes: 10, sections: 2 },
  { category: 'sermon', number: 6, slug: 'people-of-basrah', en: 'To the People of Basrah', ur: 'اہلِ بصرہ کے نام', ar: 'إلى أهل البصرة', subtitleEn: 'After the Battle of the Camel', subtitleUr: 'جمل کے بعد', excerptEn: 'O people of Basrah, you were the first to revolt...', excerptUr: 'اے اہلِ بصرہ، تم نے سب سے پہلے بغاوت کی...', themes: ['history', 'advice'], minutes: 12, sections: 3 },
  { category: 'sermon', number: 7, slug: 'on-patience', en: 'On Patience', ur: 'صبر پر', ar: 'في الصبر', subtitleEn: 'The virtue of steadfastness', subtitleUr: 'صبر کی فضیلت', excerptEn: 'Patience is of two kinds: patience over what you dislike...', excerptUr: 'صبر دو قسم کا ہے...', themes: ['patience', 'ethics'], minutes: 8, sections: 2 },
  { category: 'sermon', number: 8, slug: 'on-knowledge', en: 'On Knowledge and Ignorance', ur: 'علم و جہالت', ar: 'في العلم والجهل', subtitleEn: 'The light of knowledge', subtitleUr: 'علم کی روشنی', excerptEn: 'Knowledge is a venerable estate, good as a friend...', excerptUr: 'علم معزز مال ہے، اچھا دوست...', themes: ['knowledge', 'wisdom'], minutes: 10, sections: 2 },
  { category: 'sermon', number: 9, slug: 'on-death', en: 'On Death', ur: 'موت پر', ar: 'في الموت', subtitleEn: 'Remembering the hereafter', subtitleUr: 'آخرت کی یاد', excerptEn: 'Every soul shall taste death. How strange that one hopes for the eternal...', excerptUr: 'ہر نفس موت کا مذاق چکھے گی...', themes: ['death', 'hereafter'], minutes: 8, sections: 2 },
  { category: 'sermon', number: 10, slug: 'on-poverty', en: 'On Poverty and Wealth', ur: 'فقر و دولت', ar: 'في الفقر والغنى', subtitleEn: 'True richness and poverty', subtitleUr: 'حقیقی غنی و فقیر', excerptEn: 'Poverty is in the heart, not in the pocket...', excerptUr: 'فقر دل میں ہے، جیب میں نہیں...', themes: ['wealth', 'contentment'], minutes: 7, sections: 2 },
  { category: 'sermon', number: 24, slug: 'on-quran', en: 'On the Quran', ur: 'قرآن پر', ar: 'في القرآن', subtitleEn: 'The Book of Allah', subtitleUr: 'کتابِ اللہ', excerptEn: 'The Quran is the covenant of Allah, His rope stretched between heaven and earth...', excerptUr: 'قرآن اللہ کا عہد ہے، اس کی رسی...', themes: ['quran', 'guidance'], minutes: 10, sections: 2 },
  { category: 'sermon', number: 109, slug: 'on-asceticism', en: 'On Asceticism (Zuhd)', ur: 'زہد پر', ar: 'في الزهد', subtitleEn: 'Detachment from the world', subtitleUr: 'دنیا سے بے رغبتی', excerptEn: 'This world is a place of transit, not a place of rest...', excerptUr: 'یہ دنیا راہگزر ہے، ٹھہرنے کی جگہ نہیں...', themes: ['zuhd', 'hereafter'], minutes: 8, sections: 2 },
  { category: 'sermon', number: 110, slug: 'on-prayer', en: 'On Prayer', ur: 'نماز پر', ar: 'في الصلاة', subtitleEn: 'The pillar of religion', subtitleUr: 'دین کا ستون', excerptEn: 'Prayer is the pillar of your religion and the key to your success...', excerptUr: 'نماز تمہارے دین کا ستون ہے...', themes: ['prayer', 'worship'], minutes: 6, sections: 2 },
  { category: 'sermon', number: 156, slug: 'on-justice', en: 'On Justice', ur: 'عدل پر', ar: 'في العدل', subtitleEn: 'Justice as the foundation', subtitleUr: 'عدل کی بنیاد', excerptEn: 'Justice is the foundation of governance and the balance of creation...', excerptUr: 'عدل حکومت کی بنیاد ہے...', themes: ['justice', 'governance'], minutes: 9, sections: 2 },
  { category: 'sermon', number: 176, slug: 'on-hypocrisy', en: 'On Hypocrisy', ur: 'نفاق پر', ar: 'في النفاق', subtitleEn: 'Warning against hypocrites', subtitleUr: 'منافقوں سے تنبیہ', excerptEn: 'The hypocrite is like a mirage — near it appears water, but there is none...', excerptUr: 'منافق سراب کی مانند ہے...', themes: ['hypocrisy', 'character'], minutes: 7, sections: 2 },
];

const LETTERS: NahjulLocaleEntry[] = [
  { category: 'letter', number: 1, slug: 'to-muawiyah', en: 'Letter to Muawiyah', ur: 'معاویہ کو خط', ar: 'إلى معاوية', subtitleEn: 'On governance and justice', subtitleUr: 'حکمرانی و عدل', excerptEn: 'From the servant of Allah, Ali ibn Abi Talib, to Muawiyah ibn Abi Sufyan...', excerptUr: 'اللہ کے بندے علیؑ سے معاویہ کو...', themes: ['governance', 'justice'], minutes: 8, sections: 2 },
  { category: 'letter', number: 2, slug: 'to-uthman', en: 'Letter to Uthman', ur: 'عثمانؓ کو خط', ar: 'إلى عثمان', subtitleEn: 'Counsel before his martyrdom', subtitleUr: 'شہادت سے پہلے نصیحت', excerptEn: 'You have placed yourself in a position where the righteous are troubled...', excerptUr: 'تم نے ایسا مقام اختیار کیا...', themes: ['counsel', 'history'], minutes: 6, sections: 2 },
  { category: 'letter', number: 31, slug: 'to-malik-al-ashtar', en: 'Letter to Malik al-Ashtar', ur: 'مالک اشتر کو خط', ar: 'إلى مالك الأشتر', subtitleEn: 'The famous letter on governance', subtitleUr: 'حکمرانی کا مشہور خط', excerptEn: 'Develop in your heart the feeling of love for your people...', excerptUr: 'اپنے دل میں اپنی قوم سے محبت پیدا کرو...', themes: ['governance', 'justice', 'leadership'], minutes: 20, sections: 5 },
  { category: 'letter', number: 47, slug: 'to-son-hasan', en: 'Letter to Hasan (AS)', ur: 'حسنؑ کو خط', ar: 'إلى الحسن', subtitleEn: 'Fatherly counsel', subtitleUr: 'والدانہ نصیحت', excerptEn: 'My son, the world is a place of transit — take from it for your hereafter...', excerptUr: 'بیٹا، دنیا راہگزر ہے...', themes: ['family', 'advice'], minutes: 8, sections: 2 },
  { category: 'letter', number: 53, slug: 'to-umayr', en: 'Letter to Umayr ibn al-Humam', ur: 'عمیر بن حمام کو خط', ar: 'إلى عمير بن الحمام', subtitleEn: 'On the night before Ashura', subtitleUr: 'عاشورا سے پہلے کی رات', excerptEn: 'O Umayr, death is a bridge that takes the friend to the Friend...', excerptUr: 'اے عمیر، موت پل ہے جو دوست کو دوست تک لے جاتی ہے...', themes: ['martyrdom', 'karbala'], minutes: 5, sections: 2 },
  { category: 'letter', number: 45, slug: 'to-amr', en: 'Letter to Amr ibn al-As', ur: 'عمرو بن عاص کو خط', ar: 'إلى عمرو بن العاص', subtitleEn: 'Before the Battle of Siffin', subtitleUr: 'صفین سے پہلے', excerptEn: 'You have brought armies against me seeking the world...', excerptUr: 'تم دنیا کے لیے مجھ پر لشکر لائے...', themes: ['history', 'war'], minutes: 7, sections: 2 },
  { category: 'letter', number: 78, slug: 'to-kumayl', en: 'Letter to Kumayl ibn Ziyad', ur: 'کمیلؑ کو خط', ar: 'إلى كميل بن زياد', subtitleEn: 'On knowledge and the heart', subtitleUr: 'علم و دل', excerptEn: 'Hearts are containers — the best of them is the most receptive...', excerptUr: 'دل برتن ہیں — بہترین سب سے زیادہ قبول کرنے والا...', themes: ['knowledge', 'heart'], minutes: 6, sections: 2 },
  { category: 'letter', number: 80, slug: 'to-son-husayn', en: 'Letter to Husayn (AS)', ur: 'حسینؑ کو خط', ar: 'إلى الحسين', subtitleEn: 'Counsel to the Master of Martyrs', subtitleUr: 'سید الشہداء کو نصیحت', excerptEn: 'My son, be patient in the face of truth even if it is bitter...', excerptUr: 'بیٹا، حق کے سامنے صبر کرو...', themes: ['family', 'patience'], minutes: 5, sections: 2 },
];

const SAYINGS: NahjulLocaleEntry[] = [
  { category: 'saying', number: 1, slug: 'knowledge-one-hour', en: 'Knowledge Over Worship', ur: 'علمِ ایک گھڑی', ar: 'العلم ساعة', subtitleEn: "An hour's contemplation", subtitleUr: 'ایک گھڑی غور', excerptEn: "An hour's contemplation is better than a year's worship.", excerptUr: 'ایک گھڑی غور و فکر سال بھر عبادت سے بہتر ہے۔', themes: ['knowledge', 'worship'], minutes: 1, sections: 1 },
  { category: 'saying', number: 2, slug: 'brother-religion', en: 'Brother in Religion', ur: 'دینی بھائی', ar: 'الأخ في الدين', subtitleEn: 'The faithful brother', subtitleUr: 'مومن بھائی', excerptEn: 'Your brother in religion is like your own soul.', excerptUr: 'تمہارا دینی بھائی تمہاری اپنی روح کی مانند ہے۔', themes: ['brotherhood', 'faith'], minutes: 1, sections: 1 },
  { category: 'saying', number: 3, slug: 'two-friends', en: 'Two Friends', ur: 'دو دوست', ar: 'صديقان', subtitleEn: 'Time and the Quran', subtitleUr: 'وقت اور قرآن', excerptEn: 'Be friends with two: time and the Quran.', excerptUr: 'دو سے دوستی کرو: وقت اور قرآن۔', themes: ['time', 'quran'], minutes: 1, sections: 1 },
  { category: 'saying', number: 4, slug: 'poverty-riches', en: 'Poverty and Riches', ur: 'فقر و غنا', ar: 'الفقر والغنى', subtitleEn: 'True wealth', subtitleUr: 'حقیقی دولت', excerptEn: 'Poverty is in the heart, not in the pocket.', excerptUr: 'فقر دل میں ہے، جیب میں نہیں۔', themes: ['wealth', 'heart'], minutes: 1, sections: 1 },
  { category: 'saying', number: 5, slug: 'silence-wisdom', en: 'Silence is Wisdom', ur: 'خاموشی حکمت', ar: 'السكوت حكمة', subtitleEn: 'The wisdom of silence', subtitleUr: 'خاموشی کی حکمت', excerptEn: 'Silence is wisdom, and few practice it.', excerptUr: 'خاموشی حکمت ہے، اور کم لوگ اسے اپناتے ہیں۔', themes: ['silence', 'wisdom'], minutes: 1, sections: 1 },
  { category: 'saying', number: 6, slug: 'world-transit', en: 'World as Transit', ur: 'دنیا راہگزر', ar: 'الدنيا دار عبور', subtitleEn: 'Do not settle here', subtitleUr: 'یہاں نہ ٹھہریں', excerptEn: 'This world is a place of transit, not a place of rest.', excerptUr: 'یہ دنیا راہگزر ہے، ٹھہرنے کی جگہ نہیں۔', themes: ['zuhd', 'world'], minutes: 1, sections: 1 },
  { category: 'saying', number: 7, slug: 'death-reminder', en: 'Remember Death', ur: 'موت یاد رکھو', ar: 'اذكر الموت', subtitleEn: 'The destroyer of pleasures', subtitleUr: 'لذتوں کا تباہ کن', excerptEn: 'Remember death often — it destroys pleasures.', excerptUr: 'موت کو کثرت سے یاد کرو — یہ لذتوں کو تباہ کر دیتی ہے۔', themes: ['death', 'remembrance'], minutes: 1, sections: 1 },
  { category: 'saying', number: 8, slug: 'patience-key', en: 'Patience is Key', ur: 'صبر کنجی', ar: 'الصبر مفتاح', subtitleEn: 'To every relief', subtitleUr: 'ہر راحت کی', excerptEn: 'Patience is the key to every relief.', excerptUr: 'صبر ہر راحت کی کنجی ہے۔', themes: ['patience'], minutes: 1, sections: 1 },
  { category: 'saying', number: 9, slug: 'justice-foundation', en: 'Justice Foundation', ur: 'عدل بنیاد', ar: 'العدل أساس', subtitleEn: 'Of all virtues', subtitleUr: 'تمام فضائل کی', excerptEn: 'Justice is the foundation of all virtues.', excerptUr: 'عدل تمام فضائل کی بنیاد ہے۔', themes: ['justice'], minutes: 1, sections: 1 },
  { category: 'saying', number: 10, slug: 'heart-container', en: 'Hearts as Containers', ur: 'دل برتن', ar: 'القلوب أوعية', subtitleEn: 'Best heart receives most', subtitleUr: 'بہترین دل سب سے زیادہ قبول', excerptEn: 'Hearts are containers — the best receives the most.', excerptUr: 'دل برتن ہیں — بہترین سب سے زیادہ قبول کرتا ہے۔', themes: ['heart', 'knowledge'], minutes: 1, sections: 1 },
  { category: 'saying', number: 11, slug: 'friend-time', en: 'Value of Time', ur: 'وقت کی قدر', ar: 'قيمة الوقت', subtitleEn: 'Do not waste it', subtitleUr: 'ضائع نہ کرو', excerptEn: 'Do not waste your time — it is your capital.', excerptUr: 'اپنا وقت ضائع نہ کرو — یہ تمہاری سرمایہ ہے۔', themes: ['time'], minutes: 1, sections: 1 },
  { category: 'saying', number: 12, slug: 'tongue-sword', en: 'Tongue as Sword', ur: 'زبان تلوار', ar: 'اللسان سيف', subtitleEn: 'Guard your speech', subtitleUr: 'اپنی گفتگو کی حفاظت', excerptEn: 'The tongue is a sword — guard it well.', excerptUr: 'زبان تلوار ہے — اس کی اچھی حفاظت کرو۔', themes: ['speech', 'character'], minutes: 1, sections: 1 },
  { category: 'saying', number: 13, slug: 'greed-disgrace', en: 'Greed Brings Disgrace', ur: 'طمع ذلت', ar: 'الطمع ذل', subtitleEn: 'Contentment brings honor', subtitleUr: 'قناعت عزت', excerptEn: 'Greed brings disgrace; contentment brings honor.', excerptUr: 'طمع ذلت لاتی ہے؛ قناعت عزت۔', themes: ['greed', 'contentment'], minutes: 1, sections: 1 },
  { category: 'saying', number: 14, slug: 'knowledge-lost', en: 'Seek Knowledge', ur: 'علم طلب کرو', ar: 'اطلب العلم', subtitleEn: 'Even if far away', subtitleUr: 'چاہے دور ہو', excerptEn: 'Seek knowledge even if it is in China.', excerptUr: 'علم طلب کرو چاہے وہ چین میں ہو۔', themes: ['knowledge'], minutes: 1, sections: 1 },
  { category: 'saying', number: 15, slug: 'people-mirror', en: 'People as Mirror', ur: 'لوگ آئینہ', ar: 'الناس مرآة', subtitleEn: 'See yourself in others', subtitleUr: 'دوسروں میں خود دیکھو', excerptEn: 'People are a mirror for you — see your faults in them.', excerptUr: 'لوگ تمہارے لیے آئینہ ہیں — اپنی خامیاں ان میں دیکھو۔', themes: ['self-knowledge', 'character'], minutes: 1, sections: 1 },
  { category: 'saying', number: 16, slug: 'hope-fear', en: 'Hope and Fear', ur: 'امید و خوف', ar: 'الرجاء والخوف', subtitleEn: 'Wings of the believer', subtitleUr: 'مومن کے پر', excerptEn: 'Hope and fear are the two wings of the believer.', excerptUr: 'امید اور خوف مومن کے دو پر ہیں۔', themes: ['hope', 'fear', 'faith'], minutes: 1, sections: 1 },
  { category: 'saying', number: 17, slug: 'world-prison', en: 'World as Prison', ur: 'دنیا قید خانہ', ar: 'الدنيا سجن', subtitleEn: 'For the believer', subtitleUr: 'مومن کے لیے', excerptEn: 'The world is a prison for the believer and paradise for the disbeliever.', excerptUr: 'دنیا مومن کے لیے قید خانہ اور کافر کے لیے جنت ہے۔', themes: ['world', 'faith'], minutes: 1, sections: 1 },
  { category: 'saying', number: 18, slug: 'charity-shade', en: 'Charity as Shade', ur: 'صدقہ سایہ', ar: 'الصدقة ظل', subtitleEn: 'On the Day of Judgment', subtitleUr: 'قیامت کے دن', excerptEn: 'Charity is a shade on the Day of Judgment.', excerptUr: 'صدقہ قیامت کے دن سایہ ہے۔', themes: ['charity', 'hereafter'], minutes: 1, sections: 1 },
  { category: 'saying', number: 19, slug: 'forgive-win', en: 'Forgive to Win', ur: 'معاف کرو جیتو', ar: 'اعفو تفوز', subtitleEn: 'Allah loves the forgiving', subtitleUr: 'اللہ معاف کرنے والوں سے محبت', excerptEn: 'Forgive and you shall be forgiven; pardon and you shall be honored.', excerptUr: 'معاف کرو تو معاف ہو گے؛ درگزر کرو تو عزت پاؤ گے۔', themes: ['forgiveness', 'character'], minutes: 1, sections: 1 },
  { category: 'saying', number: 20, slug: 'trust-allah', en: 'Trust in Allah', ur: 'اللہ پر بھروسہ', ar: 'توكل على الله', subtitleEn: 'Reliance on the Provider', subtitleUr: 'رزق دینے والے پر', excerptEn: 'Whoever relies on Allah, He suffices him.', excerptUr: 'جو اللہ پر بھروسہ کرے، اللہ اسے کافی ہے۔', themes: ['tawakkul', 'faith'], minutes: 1, sections: 1 },
  { category: 'saying', number: 21, slug: 'anger-fire', en: 'Anger as Fire', ur: 'غصہ آگ', ar: 'الغضب نار', subtitleEn: 'Extinguish it with patience', subtitleUr: 'صبر سے بُجھائو', excerptEn: 'Anger is a fire — extinguish it with patience.', excerptUr: 'غصہ آگ ہے — صبر سے بُجھائو۔', themes: ['anger', 'patience'], minutes: 1, sections: 1 },
  { category: 'saying', number: 22, slug: 'humility-crown', en: 'Humility is Crown', ur: 'عاجزی تاج', ar: 'التواضع تاج', subtitleEn: 'The crown of the noble', subtitleUr: 'شرافت کا تاج', excerptEn: 'Humility is the crown of the noble.', excerptUr: 'عاجزی شرافت کا تاج ہے۔', themes: ['humility', 'character'], minutes: 1, sections: 1 },
  { category: 'saying', number: 23, slug: 'truth-freedom', en: 'Truth Sets Free', ur: 'حق آزاد', ar: 'الحق يحرر', subtitleEn: 'Speak truth always', subtitleUr: 'ہمیشہ سچ بولو', excerptEn: 'Truthfulness leads to righteousness, and righteousness leads to Paradise.', excerptUr: 'سچائی نیکی کی طرف لے جاتی ہے، نیکی جنت کی طرف۔', themes: ['truth', 'righteousness'], minutes: 1, sections: 1 },
  { category: 'saying', number: 24, slug: 'health-wealth', en: 'Health is Wealth', ur: 'صحت دولت', ar: 'الصحة ثروة', subtitleEn: 'Before sickness comes', subtitleUr: 'بیماری سے پہلے', excerptEn: 'Health is a crown on the heads of the healthy that only the sick see.', excerptUr: 'صحت صحت مندوں کے سر پر تاج ہے جو صرف بیمار دیکھتے ہیں۔', themes: ['health', 'gratitude'], minutes: 1, sections: 1 },
  { category: 'saying', number: 25, slug: 'night-prayer', en: 'Night Prayer', ur: 'تہجد', ar: 'قيام الليل', subtitleEn: 'Honor of the pious', subtitleUr: 'نیکوں کی عزت', excerptEn: 'The honor of the believer is in the night prayer.', excerptUr: 'مومن کی عزت تہجد میں ہے۔', themes: ['prayer', 'worship'], minutes: 1, sections: 1 },
  { category: 'saying', number: 26, slug: 'bad-companion', en: 'Bad Companion', ur: 'برا ساتھی', ar: 'الرفيق السوء', subtitleEn: "Like a blacksmith's bellows", subtitleUr: 'لوہار کی دم کی مانند', excerptEn: "A bad companion is like a blacksmith's bellows — if it does not burn you, its smoke will.", excerptUr: 'برا ساتھی لوہار کی دم کی مانند — نہ جلائے تو دھواں دے گا۔', themes: ['companionship', 'character'], minutes: 1, sections: 1 },
  { category: 'saying', number: 27, slug: 'good-word', en: 'Good Word', ur: 'اچھی بات', ar: 'الكلمة الطيبة', subtitleEn: 'Charity in itself', subtitleUr: 'صدقہ ہے', excerptEn: 'A good word is charity.', excerptUr: 'اچھی بات صدقہ ہے۔', themes: ['speech', 'charity'], minutes: 1, sections: 1 },
  { category: 'saying', number: 28, slug: 'envy-fire', en: 'Envy Consumes', ur: 'حسد کھاتا', ar: 'الحسد يأكل', subtitleEn: 'Good deeds like fire on wood', subtitleUr: 'آگ لکڑی پر', excerptEn: 'Envy consumes good deeds as fire consumes wood.', excerptUr: 'حسد نیک اعمال کو آگ لکڑی کو کھاتی ہے۔', themes: ['envy', 'character'], minutes: 1, sections: 1 },
  { category: 'saying', number: 29, slug: 'consult-men', en: 'Consult Men', ur: 'مشورہ کرو', ar: 'شاور الرجال', subtitleEn: 'See different perspectives', subtitleUr: 'مختلف زاویے', excerptEn: 'Consult men and see through their eyes.', excerptUr: 'لوگوں سے مشورہ کرو اور ان کی آنکھوں سے دیکھو۔', themes: ['consultation', 'wisdom'], minutes: 1, sections: 1 },
  { category: 'saying', number: 30, slug: 'death-gift', en: 'Death as Gift', ur: 'موت تحفہ', ar: 'الموت هدية', subtitleEn: 'For the believer', subtitleUr: 'مومن کے لیے', excerptEn: 'Death is a gift for the believer.', excerptUr: 'موت مومن کے لیے تحفہ ہے۔', themes: ['death', 'faith'], minutes: 1, sections: 1 },
];

export const NAHJUL_ENTRIES: NahjulLocaleEntry[] = [...SERMONS, ...LETTERS, ...SAYINGS];

export const NAHJUL_LOCALE_BY_ID = new Map<NahjulId, NahjulLocaleEntry>(
  NAHJUL_ENTRIES.map((entry) => [nahjulId(entry.category, entry.number), entry]),
);
